-- Chactivo Supabase-first: explicit privileges for SECURITY DEFINER functions.
-- Prepared locally only. Do not execute from this task.
-- PostgreSQL grants EXECUTE to PUBLIC by default; remove that implicit access.

revoke all on function public.handle_new_user_profile() from public;
revoke all on function public.is_admin_user(uuid) from public;
revoke all on function public.admin_create_reward(uuid, text, text, text, timestamptz, text, jsonb) from public;
revoke all on function public.admin_revoke_reward(uuid, text) from public;
revoke all on function public.get_or_create_direct_conversation(uuid) from public;
revoke all on function public.toggle_baul_like(uuid) from public;
revoke all on function public.record_baul_daily_event(uuid, text) from public;
revoke all on function public.send_baul_note(uuid, text) from public;
revoke all on function public.send_private_request(uuid, text) from public;
revoke all on function public.send_private_message(uuid, text, text, text, text, text, text, integer, jsonb) from public;
revoke all on function public.mark_private_message_receipts(uuid, uuid[], boolean) from public;
revoke all on function public.mark_private_conversation_read(uuid) from public;
revoke all on function public.respond_private_request(uuid, boolean) from public;
revoke all on function public.refresh_opin_post_metrics(uuid) from public;
revoke all on function public.record_opin_action(uuid, text) from public;
revoke all on function public.request_private_contact_share(uuid) from public;
revoke all on function public.respond_private_contact_share(uuid, uuid, boolean) from public;
revoke all on function public.revoke_private_contact_share(uuid, uuid) from public;
revoke all on function public.get_private_chat_shared_contacts(uuid, uuid[]) from public;
revoke all on function public.get_private_contact_state(uuid) from public;
revoke all on function public.get_my_moderation_state() from public;
revoke all on function public.record_moderation_violation(text, text, integer, text) from public;
revoke all on function public.record_moderation_event(uuid, text, jsonb) from public;
revoke all on function public.admin_create_moderation_action(uuid, text, text, timestamptz) from public;
revoke all on function public.admin_revoke_moderation_action(uuid) from public;
revoke all on function public.admin_delete_public_messages(text, uuid, boolean) from public;
revoke all on function public.admin_delete_public_message(text, uuid) from public;
revoke all on function public.create_system_notification(uuid, text, text, text, text, text, text, uuid) from public;
revoke all on function public.admin_broadcast_system_notification(text, text, text, text, text, text, text) from public;
revoke all on function public.admin_update_report_status(uuid, text, text) from public;
revoke all on function public.send_ticket_message(uuid, text, jsonb) from public;
revoke all on function public.record_analytics_event(text, text, jsonb) from public;
revoke all on function public.get_my_analytics_day(date) from public;
revoke all on function public.get_analytics_day(date) from public;
revoke all on function public.get_my_daily_limits() from public;
revoke all on function public.increment_my_daily_limit(text) from public;
revoke all on function public.toggle_forum_vote(text, uuid, boolean) from public;
revoke all on function public.increment_forum_view(uuid) from public;
revoke all on function public.record_contact_safety_event(uuid, text, text, text, integer, uuid, jsonb) from public;
revoke all on function public.increment_my_event_participation() from public;
revoke all on function public.profile_system_write_authorized(uuid) from public;
revoke all on function public.get_my_verification_status() from public;
revoke all on function public.record_user_connection() from public;
revoke all on function public.set_my_verification(boolean) from public;

-- Internal trigger functions are not callable by client roles.
revoke all on function public.sync_event_attendee_count() from public;
revoke all on function public.sync_forum_reply_count() from public;

grant execute on function public.is_admin_user(uuid) to authenticated;
grant execute on function public.get_my_active_rewards() to authenticated;
grant execute on function public.admin_create_reward(uuid, text, text, text, timestamptz, text, jsonb) to authenticated;
grant execute on function public.admin_revoke_reward(uuid, text) to authenticated;
grant execute on function public.get_or_create_direct_conversation(uuid) to authenticated;
grant execute on function public.toggle_baul_like(uuid) to authenticated;
grant execute on function public.record_baul_daily_event(uuid, text) to authenticated;
grant execute on function public.send_baul_note(uuid, text) to authenticated;
grant execute on function public.send_private_request(uuid, text) to authenticated;
grant execute on function public.send_private_message(uuid, text, text, text, text, text, text, integer, jsonb) to authenticated;
grant execute on function public.mark_private_message_receipts(uuid, uuid[], boolean) to authenticated;
grant execute on function public.mark_private_conversation_read(uuid) to authenticated;
grant execute on function public.respond_private_request(uuid, boolean) to authenticated;
grant execute on function public.refresh_opin_post_metrics(uuid) to authenticated;
grant execute on function public.record_opin_action(uuid, text) to authenticated;
grant execute on function public.request_private_contact_share(uuid) to authenticated;
grant execute on function public.respond_private_contact_share(uuid, uuid, boolean) to authenticated;
grant execute on function public.revoke_private_contact_share(uuid, uuid) to authenticated;
grant execute on function public.get_private_chat_shared_contacts(uuid, uuid[]) to authenticated;
grant execute on function public.get_private_contact_state(uuid) to authenticated;
grant execute on function public.get_my_moderation_state() to authenticated;
grant execute on function public.record_moderation_violation(text, text, integer, text) to authenticated;
grant execute on function public.record_moderation_event(uuid, text, jsonb) to authenticated;
grant execute on function public.admin_create_moderation_action(uuid, text, text, timestamptz) to authenticated;
grant execute on function public.admin_revoke_moderation_action(uuid) to authenticated;
grant execute on function public.admin_delete_public_messages(text, uuid, boolean) to authenticated;
grant execute on function public.admin_delete_public_message(text, uuid) to authenticated;
grant execute on function public.create_system_notification(uuid, text, text, text, text, text, text, uuid) to authenticated;
grant execute on function public.admin_broadcast_system_notification(text, text, text, text, text, text, text) to authenticated;
grant execute on function public.get_top_20_active_users() to authenticated;
grant execute on function public.admin_update_report_status(uuid, text, text) to authenticated;
grant execute on function public.send_ticket_message(uuid, text, jsonb) to authenticated;
grant execute on function public.record_analytics_event(text, text, jsonb) to authenticated;
grant execute on function public.get_my_analytics_day(date) to authenticated;
grant execute on function public.get_analytics_day(date) to authenticated;
grant execute on function public.get_my_daily_limits() to authenticated;
grant execute on function public.increment_my_daily_limit(text) to authenticated;
grant execute on function public.toggle_forum_vote(text, uuid, boolean) to authenticated;
grant execute on function public.increment_forum_view(uuid) to anon, authenticated;
grant execute on function public.record_contact_safety_event(uuid, text, text, text, integer, uuid, jsonb) to authenticated;
grant execute on function public.increment_my_event_participation() to authenticated;
grant execute on function public.profile_system_write_authorized(uuid) to authenticated;
grant execute on function public.get_my_verification_status() to authenticated;
grant execute on function public.record_user_connection() to authenticated;
grant execute on function public.set_my_verification(boolean) to authenticated;
